const getters = {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  enum: state => state.app.enum,
  commonEnum: state => state.app.commonEnum,
  guanranteeEnum: state => state.app.guanranteeEnum,
  breadcrumbInfo: state => state.app.breadcrumbInfo,
  itrusConfigStatus: state => state.app.itrusConfigStatus,
  loginType: state => state.user.loginType,
  token: state => state.user.token,
  roles: state => state.user.roles,
  name: state => state.user.name,
  currentUser: state => state.user.currentUser,
  currentMenu: state => state.user.currentMenu,
  mobileNo: state => state.user.mobileNo,
  routePermission: state => state.permission.routers,
  backlogList: state => state.message.backlogList,
  noticeList: state => state.message.noticeList,
  noticeUnreadNum: state => state.message.noticeUnreadNum,
  backlogNum: state => state.message.backlogNum,
  warningNum: state => state.message.warningNum,
  // base
  service: state => state.base.service,
  prodects: state => state.base.prodects,
  mapProducts: state => state.base.mapProducts,
  businessStatus: state => state.base.businessStatus,
  loanProducts: state => state.base.loanProducts,
  approvalStatus: state => state.base.approvalStatus,
  applyStatus: state => state.base.applyStatus,
  customerStatus: state => state.base.customerStatus,
  companyRole: state => state.base.companyRole,
  companyType: state => state.base.companyType,
  cooperativeEnterprise: state => state.base.cooperativeEnterprise,
  regions: state => state.base.regions,
  province: state => state.base.province,
  city: state => state.base.city,
  county: state => state.base.county,
  street: state => state.base.street,
  newUserFlag: state => state.base.newUserFlag
}

export default getters
